version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/build
    steps:
      - checkout

      - run: mkdir /tmp/test-results && cp rspec.xml /tmp/test-results/

      - type: store_test_results
        path: /tmp/test-results
