version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/build
    environment:
      CIRCLE_NODE_TOTAL: 2
    steps:
      - checkout

      - run: mkdir -p /tmp/test-results/rspec && cp *.xml /tmp/test-results/rspec/
      - run: circleci tests glob spec/*_spec.rb | circleci tests split --split-by=timings --index=0 --total=2

      - type: store_test_results
        path: /tmp/test-results

      - run: ls $CIRCLE_INTERNAL_TASK_DATA || true
