version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/build
    steps:
      - checkout

      - type: cache-restore
        key: gems-{{ checksum "Gemfile.lock" }}

      - run: bundle install -j4 --retry=3 --path vendor/bundle

      - type: cache-save
        key: gems-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rspec --format RspecJunitFormatter --out /tmp/test-results/rspec/junit.xml --format progress

      - type: store_test_results
        path: /tmp/test-results

      - type: store_artifacts
        path: /tmp/test-results
