version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/build
    steps:
      - checkout

      - run: mkdir -p /tmp/test-results/rspec && cp *.xml /tmp/test-results/rspec/

      - type: store_test_results
        path: /tmp/test-results
